import { HorizontalBox } from "std-widgets.slint";
import { CustomToggleSwitch } from "components/CustomToggleSwitch.slint";
import { DialogWindow } from "./dialog.slint";

export component SettingsButton inherits Rectangle {
    callback clicked;
    property <bool> hover <=> touch.has-hover;

    width: 22px;
    height: 22px;

    Image {
        height: 100%;
        width: 100%;
        source: @image-url("images/settings.png");
        rotation-angle: root.hover ? 0deg : 240deg;
        animate rotation_angle { duration: 200ms; easing: ease;}
    }
    touch := TouchArea {
        width: root.width;
        height: root.height;
    }
}

export component AppWindow inherits Window {
    in property <string> window_title;
    in property <string> status;
    in property <string> error;
    //
    in-out property <bool> connection_switch_enabled <=> connection_switch.enabled;
    in-out property <bool> connection_switch_checked <=> connection_switch.checked;

    // callbacks
    callback connection_switch_toggled <=> connection_switch.toggled;

    // colors
    property <[color]> warp_in_rust_text_color_gradient: [#ff7017, #871e04, #ad4605];

    width: 300px;
    height: 400px;
    title: window_title;
    default-font-size: 16px;
    background: black;

    block1 := VerticalLayout {
        preferred-width: 100%;
        
        HorizontalLayout {
            padding-top: 30px;
            preferred-width: 100%;
            height: 25%;
            alignment: center;

            Text {
                horizontal-alignment: left;
                text: "WARP";
                font-size: 40px;
                font-weight: 700;
                color: @linear-gradient(90deg, warp_in_rust_text_color_gradient[0] 0%, warp_in_rust_text_color_gradient[1] 50%, warp_in_rust_text_color_gradient[2] 100%);
            }
        }
        HorizontalLayout {
            preferred-width: 100%;
            alignment: center;

            connection_switch := CustomToggleSwitch {
                indicator_width: 105%;
                switch_color: #ff7017;
            }
        }
        VerticalLayout {
            padding-top: 30px;

            HorizontalLayout {
                alignment: center;

                Text {
                    text: status;
                    color: white;
                    height: 20px;
                }
            }
            HorizontalLayout {
                alignment: center;

                Text {
                    text: error;
                    color: red;
                    height: 20px;
                }
            }
        }
    }
    VerticalLayout {
        alignment: end;
        Rectangle {
            preferred-width: 100%;
            height: 40px;
            background: #2A3033;

            HorizontalLayout {
            alignment: start;
                HorizontalLayout {
                VerticalLayout {
                    alignment: center;
                    Image {
                        width: 30px;
                        height: 22px;
                        source: @image-url("images/watermark.png");
                    }
                }
                VerticalLayout {
                    alignment: center;
                    padding-left: 5px;
                    Text {
                        text: "CLOUDFLARE WARP";
                        font-size: 11px;
                        font-weight: 8900;
                        color: #ff7017;
                    }
                    Text {
                        text: "WRITTEN IN RUST";
                        font-size: 8px;
                        font-weight: 800;
                        color: white;
                    }
                }
                }
            }
            HorizontalBox {
                alignment: end;
                VerticalLayout {
                    alignment: center;

                    SettingsButton {}
                }
            }
        }
    }
}