import { HorizontalBox } from "std-widgets.slint";
import { CustomToggleSwitch } from "components/CustomToggleSwitch.slint";

export component SettingsButton inherits Rectangle {
    callback clicked;
    property <bool> hover <=> touch.has-hover;

    width: 22px;
    height: 22px;

    Image {
        height: 100%;
        width: 100%;
        source: @image-url("images/settings.png");
        rotation-angle: root.hover ? 0deg : 240deg;
        animate rotation_angle { duration: 200ms; easing: ease;}
    }
    touch := TouchArea {
        width: root.width;
        height: root.height;
    }
}

export component AppWindow inherits Window {
    in property <string> window_title;
    in property <string> status;
    //
    in-out property <bool> connection_switch_enabled <=> connection_switch.enabled;
    in-out property <bool> connection_switch_checked <=> connection_switch.checked;

    // callbacks
    callback connection_switch_toggled <=> connection_switch.toggled;

    // colors
    property <[color]> warp_in_rust_text_color_gradient: [#ff7017, #871e04, #ad4605];
    
    width: 300px;
    height: 400px;
    title: window_title;
    default-font-size: 20px;
    background: black;

    block1 := VerticalLayout {
        preferred-width: 100%;

        HorizontalLayout {
            padding-top: 30px;
            preferred-width: 100%;
            height: 25%;
            alignment: center;
            
            Text {
                horizontal-alignment: left;
                text: "WARP";
                font-size: 40px;
                font-weight: 700;
                color: @linear-gradient(90deg, warp_in_rust_text_color_gradient[0] 0%, warp_in_rust_text_color_gradient[1] 50%, warp_in_rust_text_color_gradient[2] 100%);
            }
            Text {
                horizontal-alignment: left;
                text: "in rust";
                font-size: 18px;
                font-weight: 500;
                color: @linear-gradient(90deg, warp_in_rust_text_color_gradient[0] 0%, warp_in_rust_text_color_gradient[1] 50%, warp_in_rust_text_color_gradient[2] 100%);
            }
        }
        HorizontalLayout {
            preferred-width: 100%;
            alignment: center;

            connection_switch := CustomToggleSwitch {
                indicator_width: 105%;
                switch_color: #ff7017;
            }
        }
        HorizontalLayout {
            alignment: center;
            padding-top: 30px;
            Text {
                text: status;
                color: white;
            }
        }
    }
    VerticalLayout {
        alignment: end;
        Rectangle {
            preferred-width: 100%;
            height: 40px;
            background: #2A3033;

            HorizontalBox {
                alignment: end;

                SettingsButton {}
            }
        }
    }
}