import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
export component DialogWindow inherits Window {
    in property <string> type;
    in property <string> dialog_text;
    in property <string> dialog_type;

    callback dialog_clicked_ok;

    min-width: 250px;
    max-width: 800px;
    height: 150px;
    title: "Dialog";
    background: black;

    VerticalBox {
        HorizontalBox {
            Image {
                width: 40px;
                source: dialog_type == "error" ? @image-url("images/error.png") : @image-url("images/warning.png");
            }
            VerticalBox {
                Text {
                    text: dialog_type == "error" ? "Error!" : (dialog_type == "warning" ? "Warning" : dialog_type);
                    color: white;
                    font-size: 20px;
                    height: 20px;
                }
                Text {
                    text: dialog_text;
                    color: white;
                    font-size: 14px;
                }
            }
        }
        Button {
            height: 30px;
            text: "OK";
            clicked => {
                dialog_clicked_ok();
            }
        }
    }
}