import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
export component DialogWindow inherits Window {
    in property <string> type;
    in property <string> dialog_text;

    min-width: 250px;
    max-width: 800px;
    height: 130px;
    title: "Dialog";
    background: black;

    VerticalBox {
        HorizontalBox {
            Image {
                width: 40px;
                source: @image-url("images/error.png");
            }
            VerticalBox {
                Text {
                    text: "Error!";
                    color: white;
                    font-size: 20px;
                    height: 20px;
                }
                Text {
                    text: dialog_text;
                    color: white;
                    font-size: 14px;
                }
            }
        }
        Button {
            height: 30px;
            text: "OK";
        }
    }
}